### ISSUE TITLE
can not switch sdModelCheckpoint since 2 days ago.

### ISSUE THREAD

**Issue by snmoney** [Kryptortio/SDAtom-WebUi-us#25] opened 2023-05-05 12:29 UTC
queue JSON looks fine, with the correct checkpoint setting. 
each task has the different checkpoint.
but the queue excuted  by same checkpoint. (SD current selection)

python: 3.10.6  •  torch: 1.13.1+cu117  •  xformers: 0.0.16rc425  •  gradio: 3.28.1  •  commit: [5ab7f213]

**Comment by Kryptortio** [comment] 2023-05-05 14:36
I suggest that when you run into an issue, check this first https://github.com/Kryptortio/SDAtom-WebUi-us#troubleshooting

More specifically, try activating verbose and check/copy what happens when it tries to switch mode/checkpoint.

**Comment by AudieMurphy135** [comment] 2023-05-08 15:34
I'm also running into the same issue. It doesn't switch checkpoints when starting the queue or moving to the next item. It only uses the checkpoint that is currently selected at the top of the WebUI. I'm using the latest version of this extension and 1.1.1 of the WebUI. I've also run into this issue on 1.0.

I updated this extension this morning, which is what seems to have broken it. I originally downloaded this extension on April 16, so whichever version was available then is what worked fine.

There are no errors when running the queue, however this error shows up when refreshing the page:

`Javascript promise error (can be caused by something other than this script): TypeError: Cannot read properties of undefined (reading 'props')`

I've tried running this with all other extensions disabled, so it doesn't appear to be a conflict.

The F12 console in Chrome shows this error:

```
Blocks.svelte:230 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'props')
    at Blocks.svelte:230:30
    at Array.forEach (<anonymous>)
    at ye (Blocks.svelte:215:9)
    at Blocks.svelte:294:7
![Screenshot 2023-05-08 083349](https://user-images.githubusercontent.com/41809084/236866349-af5c339b-b54a-415d-b320-564b5b121711.png)

(anonymous) @ Blocks.svelte:230
ye @ Blocks.svelte:215
(anonymous) @ Blocks.svelte:294
Promise.then (async)
ze @ Blocks.svelte:289
(anonymous) @ Blocks.svelte:343
(anonymous) @ index.mjs:1170
Cn @ index.mjs:1170
r @ Slider.svelte:21
(anonymous) @ index.mjs:1115
(anonymous) @ index.mjs:1114
e.$$.update @ Range.svelte:25
Mn @ index.mjs:1269
en @ index.mjs:1233
Promise.then (async)
Yt @ index.mjs:1184
Rn @ index.mjs:2066
(anonymous) @ index.mjs:2104
d @ Tabs.svelte:10
n @ index-1e4fc636.js:1
(anonymous) @ index.mjs:2102
T @ Tabs.svelte:48
D @ Tabs.svelte:67
a @ Tabs.svelte:71
triggerEvent @ state.utils.js?1683558325.1851387:9
restoreTabs @ state.core.js?1683558325.1841388:178
load @ state.core.js?1683558325.1841388:82
(anonymous) @ state.core.js?1683558325.1841388:59
```

**Comment by MNeMoNiCuZ** [comment] 2023-05-14 09:09
I also have this issue since I got an update to Automatic 1111.
It switches the model in the top left model drop-down, but it doesn't actually change model (nothing in SD console), and it doesn't actually do anything.

**Comment by Kryptortio** [comment] 2023-05-14 09:22
Please confirm that you have the latest version of the script (including [the fix](https://github.com/Kryptortio/SDAtom-WebUi-us/commit/9ede5dfe52730a15cdd520fc264a34fc7ea6ba14) specifically for this), like I mentioned above the [troubleshooting section](5f6f1556d1) is a good place to start. In particular activating verbose console and sharing all the output would be helpful when reporting issues.

**Comment by MNeMoNiCuZ** [comment] 2023-05-14 09:24
Sorry, I don't quite know how the updating works with this one.
I have the latest version of the script using the update checker in extensions. Will that not work to get that fix?

Also, how do I activate verbose logging?

New to this :)

**Comment by Kryptortio** [comment] 2023-05-14 09:36
There is a version column in the extension tab that should say

> [caf588e2 (Mon May 8 17:22:44 2023)](https://github.com/Kryptortio/SDAtom-WebUi-client-queue-ext/commit/caf588e2aadeba8e530b129aca3c33f34faea016)

If you have the latest version. If not, reinstalling the extension could solve it (data is stored in the browser and should not be lost).

"Verbose console" is a checkbox listed if you click the script settings button.

**Comment by MNeMoNiCuZ** [comment] 2023-05-14 09:51
![image](https://github.com/Kryptortio/SDAtom-WebUi-us/assets/60541708/4d447086-cef7-45bd-a7e3-88f4d9ad46cf)
In that case I do have the latest version.

I'll try a reinstall anyway.

I added the (SDAtom-WebUi-us) repository to see if it was needed now, and it didn't change anything. I assume I don't need to have that one?

Here's a sample log where it should have switched model twice:

`11:49:21: Saving script settings
11:49:25: updateQueueState: old length:2 new length:2
11:49:25: updateQueueState: Saving current queue state 2
11:49:26: updateQueueState: old length:2 new length:2
11:49:26: updateQueueState: Saving current queue state 2
11:49:34: toggleProcessButton:undefined
11:49:34: toggleProcessButton:true
11:49:34: Processing started
11:49:34: executeNewTask: working=false processing=true
11:49:34: executeNewTask: found next work item with index 0, quantity 1 and type t2i
11:49:34: getValueJSON: type=t2i
11:49:34: loadJson: t2i
11:49:34: loadJson: Trying to load model: Checkpoints\darksun_v20.safetensors [9a4d193dfc]
11:49:34: setCheckpointWithPost: Checkpoints\darksun_v20.safetensors [9a4d193dfc]
11:49:34: switchTabAndWait: t2i
11:49:34: updateStatus: active type changed to:t2i
11:49:35: Switched active tab from other to t2i
11:49:35: loadJson: loaded: prompt: {PROMPT HERE} | restoreFace:false-->true
11:49:35: clickStartButton: working false waiting false type t2i
11:49:35: clickStartButton: work has started
11:49:35: updateQueueState: old length:2 new length:2
11:49:35: updateQueueState: Saving current queue state 2
11:49:35: Started working on t2i queue item 1 (0 more to go)
11:49:35: waitForTaskToComplete: Waiting to complete work for t2i
11:50:24: Work is complete for t2i
11:50:24: executeNewTask: working=false processing=true
11:50:24: Completed work on queue item after 0 minutes 49 seconds
11:50:24: executeNewTask: found next work item with index 1, quantity 1 and type t2i
11:50:24: getValueJSON: type=t2i
11:50:24: loadJson: t2i
11:50:24: loadJson: Trying to load model: Checkpoints\revAnimated_v122.safetensors [4199bcdd14]
11:50:24: setCheckpointWithPost: Checkpoints\revAnimated_v122.safetensors [4199bcdd14]
11:50:24: loadJson: loaded: prompt:{PROMPT HERE} | restoreFace:true-->false
11:50:24: clickStartButton: working false waiting false type t2i
11:50:24: clickStartButton: work has started
11:50:24: updateQueueState: old length:2 new length:2
11:50:24: updateQueueState: Saving current queue state 2
11:50:24: Started working on t2i queue item 2 (0 more to go)
11:50:24: waitForTaskToComplete: Waiting to complete work for t2i
11:51:12: Work is complete for t2i
11:51:12: executeNewTask: working=false processing=true
11:51:12: Completed work on queue item after 0 minutes 48 seconds
11:51:12: executeNewTask: No more tasks found
11:51:12: toggleProcessButton:false
11:51:12: Processing ended`

**Comment by Kryptortio** [comment] 2023-05-14 13:16
I think @MNeMoNiCuZ is having a new issue, the latest version seems to have broken the fix I made previously. I changed it and tried to make it so that it will not break again on the next update.

So update to the latest version of the script (1.3.1, it should now say the version in the console even if you are running the extension instead of the user script).

> I added the (SDAtom-WebUi-us) repository to see if it was needed now, and it didn't change anything. I assume I don't need to have that one?

No you only need one of [them](https://github.com/Kryptortio/SDAtom-WebUi-us#installation).

Let me know it that solves this issue for you.

**Comment by MNeMoNiCuZ** [comment] 2023-05-14 15:07
Hmm, now it did something.
For the first queue index, it didn't change the model. It kept whatever it was already at.
For the second queue index, it changed model, but not to the one provided. Instead it picked the first model index (alphabetically first in list of models).

Here's the new log:

> * Running SDAtom-WebUi-us version 1.3.1 using (not user script) with browser Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0 stable-diffusion-webui version version: v1.2.1  •  python: 3.10.9  •  torch: 2.0.0+cu118  •  xformers: 0.0.17  •  gradio: 3.29.0  •  checkpoint: fbcf965a62 ⠀•⠀Cozy Nest: ⠀v2.0.1
17:02:04: toggleProcessButton:undefined
17:02:04: toggleProcessButton:true
17:02:04: Processing started
17:02:04: executeNewTask: working=false processing=true
17:02:04: executeNewTask: found next work item with index 0, quantity 1 and type t2i
17:02:04: getValueJSON: type=t2i
17:02:04: loadJson: t2i
17:02:04: loadJson: Trying to load model: Checkpoints\darksun_v20.safetensors [9a4d193dfc]
17:02:04: setCheckpointWithPost: Checkpoints\darksun_v20.safetensors [9a4d193dfc]
17:02:04: setCheckpointWithPost: found fn_index 722
17:02:04: loadJson: loaded:
17:02:04: clickStartButton: working false waiting false type t2i
17:02:04: setCheckpointWithPost: repsonse: 422-Unprocessable Entity: {}
17:02:04: clickStartButton: work has started
17:02:04: updateQueueState: old length:2 new length:2
17:02:04: updateQueueState: Saving current queue state 2
17:02:04: Started working on t2i queue item 1 (0 more to go)
17:02:04: waitForTaskToComplete: Waiting to complete work for t2i
17:03:02: Work is complete for t2i
17:03:02: executeNewTask: working=false processing=true
17:03:02: Completed work on queue item after 0 minutes 57 seconds
17:03:02: executeNewTask: found next work item with index 1, quantity 1 and type t2i
17:03:02: getValueJSON: type=t2i
17:03:02: loadJson: t2i
17:03:02: loadJson: Trying to load model: Checkpoints\revAnimated_v122.safetensors [4199bcdd14]
17:03:02: setCheckpointWithPost: Checkpoints\revAnimated_v122.safetensors [4199bcdd14]
17:03:02: setCheckpointWithPost: found fn_index 722
17:03:02: loadJson: loaded: prompt: [PROMPT] | restoreFace:true-->false
17:03:02: clickStartButton: working false waiting false type t2i
17:03:02: clickStartButton: work has started
17:03:02: updateQueueState: old length:2 new length:2
17:03:02: updateQueueState: Saving current queue state 2
17:03:02: Started working on t2i queue item 2 (0 more to go)
17:03:02: waitForTaskToComplete: Waiting to complete work for t2i
17:03:05: setCheckpointWithPost: repsonse: 200-OK: {}
17:03:59: Work is complete for t2i
17:03:59: executeNewTask: working=false processing=true
17:03:59: Completed work on queue item after 0 minutes 57 seconds
17:03:59: executeNewTask: No more tasks found
17:03:59: toggleProcessButton:false
17:03:59: Processing ended

**Comment by Kryptortio** [comment] 2023-05-14 15:21
Looks like you are using subfolders instead of having all of them in the \stable-diffusion-webui\models\Stable-diffusion folder. I haven't tried that before but I see it requires changing the format a bit to support this. I have pushed a new version that hopefully solves this as well.

**Comment by MNeMoNiCuZ** [comment] 2023-05-14 15:29
Ah, yes I was indeed. The same for LoRAs and stuff, just to have better sorting/filtering of things.

Now it's unable to launch Automatic1111. It gets stuck at 44% each time.
![image](https://github.com/Kryptortio/SDAtom-WebUi-us/assets/60541708/1461f28d-5f10-4118-9648-008d7ccbf525)

**Comment by Kryptortio** [comment] 2023-05-14 15:42
That's strange, however it's likely not related to this change as the small piece of code I added only gets executed when the switch is about to happen. I noticed you had something else I haven't seen before at the end of your url `?__theme=dark`. I tried adding that to mine an that actually stops the script from running completely for me but that's only an issue for the user script version not the extension.

But like I said something else has likely happened, you should check if there is something happening in the command line output (cmd/python window). You can also press F12 and going to the console tab before loading the page to see if there is some other script causing issues there.

**Comment by MNeMoNiCuZ** [comment] 2023-05-14 17:35
You are right, it seems like it was unrelated. I restarted several times and I still got the issue, and when I moved the Queue extension out of the extensions folder, it suddenly worked, which is why I suspected it. But putting it back now just straight up worked, regardless of dark theme or not. That was just added to my launch at some point, I didn't add it, not sure what's up with that :D


It looks like it's working now! Both the first and second in queue, with checkpoints in subfolders!

> * Running SDAtom-WebUi-us version 1.3.2 using (not user script) with browser Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/113.0 stable-diffusion-webui version version: v1.2.1  •  python: 3.10.9  •  torch: 2.0.0+cu118  •  xformers: 0.0.17  •  gradio: 3.29.0  •  checkpoint: 77b4c5882f
19:32:00: refreshSettings: saved settings:0
19:32:00: Loaded saved queue:2
19:32:00: appendQueueItem: quantity:1 type:t2i
19:32:00: Added new t2i queue item (1x)
19:32:00: appendQueueItem: quantity:1 type:t2i
19:32:00: Added new t2i queue item (1x)
19:32:00: updateQueueState: old length:2 new length:2
19:32:00: updateQueueState: Saving current queue state 2
19:32:00: generateMainUI: Completed
19:32:00: initAWQ: stack = @http://127.0.0.1:7860/file=extensions/SDAtom-WebUi-client-queue-ext/javascript/SDAtom-WebUi-us.user.js?1684077784.0346107:489:21
19:32:01: Javascript promise error (can be caused by something other than this script): TypeError: Y[R[ee]] is undefined
19:32:01: Javascript promise error (can be caused by something other than this script): TypeError: Y[R[ee]] is undefined
19:32:01: Javascript promise error (can be caused by something other than this script): TypeError: Y[R[ee]] is undefined
19:32:01: updateStatus: active type changed to:other
19:32:11: toggleProcessButton:undefined
19:32:11: toggleProcessButton:true
19:32:11: Processing started
19:32:11: executeNewTask: working=false processing=true
19:32:11: executeNewTask: found next work item with index 0, quantity 1 and type t2i
19:32:11: getValueJSON: type=t2i
19:32:11: loadJson: t2i
19:32:11: loadJson: Trying to load model: Checkpoints\darksun_v20.safetensors [9a4d193dfc]
19:32:11: setCheckpointWithPost: Checkpoints\darksun_v20.safetensors [9a4d193dfc]
19:32:11: setCheckpointWithPost: found fn_index 625
19:32:11: switchTabAndWait: t2i
19:32:11: updateStatus: active type changed to:t2i
19:32:11: Switched active tab from other to t2i
19:32:11: loadJson: loaded: prompt: [PROMPT] | sampleMethod:DPM++ SDE Karras-->UniPC | width:384-->512 | height:384-->576 | restoreFace:false-->true | script:Prompts from file or textbox-->None
19:32:11: clickStartButton: working false waiting false type t2i
19:32:11: Javascript promise error (can be caused by something other than this script): TypeError: Y[R[ee]] is undefined
19:32:11: Javascript promise error (can be caused by something other than this script): TypeError: Y[R[ee]] is undefined
19:32:11: clickStartButton: work has started
19:32:11: updateQueueState: old length:2 new length:2
19:32:11: updateQueueState: Saving current queue state 2
19:32:11: Started working on t2i queue item 1 (0 more to go)
19:32:11: waitForTaskToComplete: Waiting to complete work for t2i
19:32:16: setCheckpointWithPost: repsonse: 200-OK: {}
19:33:11: Work is complete for t2i
19:33:11: executeNewTask: working=false processing=true
19:33:11: Completed work on queue item after 0 minutes 59 seconds
19:33:11: executeNewTask: found next work item with index 1, quantity 1 and type t2i
19:33:11: getValueJSON: type=t2i
19:33:11: loadJson: t2i
19:33:11: loadJson: Trying to load model: Checkpoints\revAnimated_v122.safetensors [4199bcdd14]
19:33:11: setCheckpointWithPost: Checkpoints\revAnimated_v122.safetensors [4199bcdd14]
19:33:11: setCheckpointWithPost: found fn_index 625
19:33:11: loadJson: loaded: prompt:[PROMPT] | restoreFace:true-->false
19:33:11: clickStartButton: working false waiting false type t2i
19:33:12: setCheckpointWithPost: repsonse: 200-OK: {}
19:33:13: clickStartButton: work has started
19:33:13: updateQueueState: old length:2 new length:2
19:33:13: updateQueueState: Saving current queue state 2
19:33:13: Started working on t2i queue item 2 (0 more to go)
19:33:13: waitForTaskToComplete: Waiting to complete work for t2i
19:34:01: Work is complete for t2i
19:34:01: executeNewTask: working=false processing=true
19:34:01: Completed work on queue item after 0 minutes 48 seconds
19:34:01: executeNewTask: No more tasks found
19:34:01: toggleProcessButton:false
19:34:01: Processing ended

**Comment by Kryptortio** [comment] 2023-05-14 17:52
Great, thanks for the feedback.

**Closed by Kryptortio** 2023-05-14 17:52 UTC

**Comment by MNeMoNiCuZ** [comment] 2023-05-14 17:59
I think I found a repro for the issue with not being able to launch though.
It's when the latest version is combined with the latest version of CozyNest (https://github.com/Nevysha/Cozy-Nest).
If I disable/remove either extension, it works. But not when combined :(

Why must mom and dad fight? Can't we all just get along! 😭
